#!/bin/bash

export DBUS_SESSION_BUS_ADDRESS="unix:path=/run/user/1000/bus"
export XDG_RUNTIME_DIR="/run/user/1000"

/usr/bin/notify-send -u critical "LOW BATTERY" "Please charge your device!\nHibernating when 5% or lower." && paplay /usr/share/sounds/freedesktop/stereo/dialog-warning.oga
