#!/bin/env sh


menu="wofi -d"

choice="$(printf "Clone\nExtend" | $menu -p "Select a action" )"
if [ $choice == "Clone" ]; then
    id="$(wdomirror | awk '/Mirrorable output:/')"
    option="$(printf "$id" | $menu -p "Pick a display to mirror")"
    mirror="$(printf "$option" | rev | cut -d" " -f1 | rev)"
    monitor_model="$(swaymsg -t get_outputs --raw | grep "model")"
    workspace_id="$(swaymsg -t get_outputs | grep "current_workspace" | sed -n 2p | grep -o -E '[0-9]+')"
    wdomirror $mirror &
    pid=$!
    notify-send "MirrorDisplay" "Waiting 1 second.."
    sleep 1.2
    swaymsg "[pid=$pid]" move window to workspace $workspace_id
    swaymsg "[pid=$pid]" fullscreen
    notify-send "MirrorDisplay" "Window moved to workspace $workspace_id"

elif [ $choice == "Extend" ]; then
    extend="$(printf "Right\nLeft\nTop\nBottom" | $menu )"
fi
