#!/bin/bash

url="http://www.datameteo.com/meteo/weather_Stockholm"

# we get all the web page
allfile=$( wget -qO-  $url | sed 's/<br/\n/g' | sed 's/<\/span>/\n/g' | grep -i ">Sunrise");

# we get the original sunrise/sunset time values
sunrise_str=$(echo $allfile | cut -d ":" -f 2,3 | sed 's|[^0-9]*\([0-9\:]*\)|\1 |g')
sunset_str=$(echo $allfile | cut -d ":" -f 4,5 | sed 's|[^0-9]*\([0-9\:]*\)|\1 |g')

# we convert time values to Time in 24-hour format
sunset=$(/bin/date --date="$sunset_str" +%R)
sunrise=$(/bin/date --date="$sunrise_str" +%R)

sunset=$(echo $sunset | cut -d ":" -f 1)
sunrise=$(echo $sunrise | cut -d ":" -f 1)

currenttime=$(date +%H)

if [ "$currenttime" -gt $sunset ] || [  "$currenttime" -lt $sunrise ]; then
	brightnessctl --device="tpacpi::kbd_backlight" set 1 & swayidle timeout 15 'brightnessctl --device="tpacpi::kbd_backlight" set 0' resume 'brightnessctl --device="tpacpi::kbd_backlight" set 1'
elif [ "$1" ]; then
	brightnessctl --device="tpacpi::kbd_backlight" set "$1" & swayidle timeout 15 'brightnessctl --device="tpacpi::kbd_backlight" set 0' resume "brightnessctl --device='tpacpi::kbd_backlight' set $1"
else
    brightnessctl --device="tpacpi::kbd_backlight" set 0
fi

