#!/bin/bash

currenttime=`date +%H`

if [ $currenttime -gt 15 ] || [  $currenttime -lt 7 ]
then
	brightnessctl --device="tpacpi::kbd_backlight" set 1 & swayidle timeout 15 'brightnessctl --device="tpacpi::kbd_backlight" set 0' resume 'brightnessctl --device="tpacpi::kbd_backlight" set 1'
fi
